apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-orchestrator
  labels:
    app: payment-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-orchestrator
  template:
    metadata:
      labels:
        app: payment-orchestrator
    spec:
      containers:
      - name: payment-orchestrator
        image: httpsantos/payment_orchestrator:1.1
        ports:
        - containerPort: 7001
        env:
          - name: RABBIT_HOST
            value: broker
          - name: RABBIT_PORT
            value: "5672"
          - name: RABBIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbit-user
                key: username
          - name: RABBIT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbit-user
                key: password

